services:
  clinical-trials-server:
    build:
      context: ./info_mcp
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8081:8081"

  ollama:
    image: ollama/ollama:latest
    env_file:
      - .env.docker
    environment:
      - OLLAMA_MODELS=/.ollama/models
    expose:
      - "11434"
    volumes:
      - ollama_models:/.ollama

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - clinical-trials-server
    environment:
      - OLLAMA_HOST=ollama
      - CLINICAL_TRIALS_MCP_HOST=clinical-trials-server

volumes:
  ollama_models: